### ISSUE TITLE
ARC19 needs to specify explicitly that the data pointed to by the reserve address is JSON

### ISSUE THREAD

**Issue by runvnc** [algorandfoundation/ARCs#127]
Several groups such as Project Raven were uploading images at the CID specified by the reserve address, I copied that pattern, since it is not stated in the specification that it needs to be any particular file type.

There are numerous places where terms like MUST and SHOULD are used, but nowhere does it say that this CID MUST point to JSON.

So since that was the intention, it needs to be stated explicitly in this format. Also should be clarified explicitly that any JSON file is valid, rather than necessarily ARC3 format (as is implied).

**Comment by robdmoore** [comment]
I originally asked about this (because I was interested in using arc-69 and arc-19 together).

The resulting discussion was that ARC-19 could deliberately not specify what the url points to to leave future flexibility and other ARCs could be created to tackle that.

cc @cusma @pbennett

**Comment by runvnc** [comment]
Would be interesting to see where that was stated in the discussion. Patrick told me today that it was expressly intended to be used with metadata only and that not specifying that with a "MUST" was something he felt was unnecessary because it was implied by the rest of the text. Based on that claim, I made announcements on my Discord server and Twitter that I had implemented arc19 incorrectly and so had those other projects.

**Comment by robdmoore** [comment]
It feels weirdly limiting to me to assume that ARC-19 always points to “ARC-3 metadata”. They limits all kinds of potential future use cases.

sure, that was the context within which it was designed but it could be kept as a more general purpose standard that simply deals with mutable urls.

here was the original discussion by the way: https://github.com/algorandfoundation/ARCs/pull/116

**Comment by runvnc** [comment]
He did not tell me arc3, just metadata JSON.

**Comment by runvnc** [comment]
Ok, I understand what happened. He just didn't 100% agree with the actual spec that was finalized supposedly implemented his idea. To me it was sensible that Fabrice decided to leave it open. I understand that there is a strong desire here to avoid arc69, but practically speaking ensuring the file is only metadata should be another arc. So I was ultimately misinformed about the final arc form today and made an incorrect announcement. I still plan to build arc3 as an option and probably default for this but now I might have to also allow arc69 at the same time as a choice. I'm not looking forward to making an announcement that my announcement about being incorrect was incorrect though..maybe take a break from announcements.

**Comment by robdmoore** [comment]
Sure there’s heaps of references to arc 3 as examples but the core of the spec isn’t explicit.

Even the lead-in paragraph of motivation is like “there are cases where some type of mutability is desired for NFT metadata and/or digital media”

But sure, that doesn’t mean that clients will support that today since my assumption would be that most implementations would assume arc3.

Whenever I’ve minted ARC-19 using arc-3 metadata I’ve added the arc3 marker so a client could make the assumption.

I think it’s fair to say that there should be a separate arc dealing with specific uses of arc-19 with a metadata standard (which is hinted at in arc-19 anyway).

**Comment by robdmoore** [comment]
Side-note: if we did have an ARC-69+19 I vote it should be called ARC-88 :p

**Comment by runvnc** [comment]
Right, it really should have something saying arc3 at then end if that's what it is.

The discussion that specifically addresses this question as to whether the reserve (CID) can point to metadata or an image and references the ambiguity in the text is clear. @pbennett if you still disagreed at that point then you needed to reply to @fabrice102 's message or say something at some point to contradict when he specifically said he was going to leave that open.

I think it would have been quite problematic for fabrice to make another decision at that point, due to the schism related to arc3/arc69. I know there are different viewpoints on this, and different practicalities depending on projects.

**Comment by pbennett** [comment]
Someone could link to an image and *have no metadata* and be a compliant ARC19 asset.
If someone tacks #arc3 on the end it means it references an arc3 json spec and its spec is explicit.  ARC19 leaves the specific metadata spec up to others - as that's an entirely different can of worms (arc3 makes no mention of traits for eg - that's a different ARC)

Wanting a mutable URL link but to *also* have note transactions represent metadata needs to be a new ARC because nothing in ARC19, ever, says note transactions should be read - in fact it makes a point about explicitly avoiding their need - fetching all data from a single aglod call.   

If you have an asset where part of its data is in note transactions and the only way to display the asset is to fetch those, it's not ARC19 - it should be a new ARC (and could even be a super simple one).  Just please make sure there's something in the asset that makes it clear.

New ARCs should just be sequential... but ARC-88 would be kind of funny. 😂

**Comment by runvnc** [comment]
> However, ARC-19 is fully compatible with ARC-69 as ARC-69 does have the asset hash optional.

That's what fabrice said before he finalized it. He's the referee of the process. Its a process and someone has this role because there are different people involved. He specifically said that it was compatible with arc69, and many projects have been using it that way. You specifically did not say that it MUST be metadata. That is the key usage of those terms in these types of documents. and it failed to be included here. @pbennett again, it was a requirement of the process to contradict him if you felt that the standard should not proceed with that interpretation.

I am planning on making arc3 the default anyway with arc19 as soon as I can get to it. Not because it actually makes more sense to me, but because I am tired of the conflict.

**Comment by SudoWeezy** [comment]
Hello guys, here are my 2 cents on the subject.

I don't think you implemented (ARC19 or AR69) wrong. In my opinion, the main issue is that we are using one part of the 69 (note) and one part of the 19 (mutable ipfs template).  And neither of those 2 ARCs cover the compatibility for this. 

From the Motivation section of arc 19:

> An asset-config transaction may include a note, but it is limited to 1KB and accessing this value requires clients to use an indexer to iterate/retrieve the values.
>Using the reserve address in this way means that what an ASA 'points to' for metadata can be changed with a single asset config transaction, changing only the 32-bytes of the reserve address. The new value is accessible via even non-archival nodes with a single call to the /v2/assets/xxx REST endpoint.

So based on those 2 quotes, we can see the purpose of ARC 19.

From a technical point of view, it makes more sense to use ARC 3 + ARC 19 if you want mutability for metadata because you already force the client to fetch the URL. 
When using ARC 19 + ARC 69, you must fetch IPFS content and the indexer's new note txn.
That is why it might not have been covered inside the ARC-19.

However. Even if the ARC-19 mutable ipfs template was not **INTENDED** to be used with ARC-69, I understand that it was maybe more convenient for some project creators to keep using ARC-69. 


So I see 2 options:
- We update the ARC-69, which is living, to mention the possibility of using a mutable ipfs template (ARC-19 like) @ChrisAntaki @TommyAlex79 @algokittens 
- We create a new ARC that says explicitly that the Url is linked to a mutable Media file and the metadata to the indexer note.

**Comment by ChrisAntaki** [comment]
I propose updating ARC19 to remind people the #arc3 suffix is necessary for valid ARC3 URLs

**Comment by ChrisAntaki** [comment]
Using ARC69 isn't just about convenience, it's also loads media more efficiently, so it provides a better user experience

**Comment by SudoWeezy** [comment]
I agree with your points @ChrisAntaki, ARC-69 also has an advantage for fetching the URL. That's why I don't want to remove this option from using the mutable IPFS content.

**Comment by 1fatalix1** [comment]
I would like to add to the conversation from the perspective of project creator.
The reason why I decided to use arc19/arc69 is because arc19/arc3 requires two files to be pinned to IPFS network and in my opinion this is hugely inefficient. 
It already takes about 30 seconds to process one mutation and another pin would only increase that time. 
Also I use Pinata as IPFS provider and I'm restricted by the amount of pins so adding another pin for each mutation would mean that I would run out of available pins twice as fast. Of course there are some services that offer unlimited pins but I cannot simply assume it will stay that way. 
People don't realise that this is not much of a problem for static NFTs as in case of IPFS provider failure all they have to do is to find another provider and pin their files there. For mutable NFTs that are dynamically generated like Project R4V3N this would be a catastrophic failure with no means of recovery.
Arc69 is a sort of a fallback for me as based on the metadata I'm always in position to recover the actual image if IPFS side of things suddenly disappears and retain full mutations history.
I've said it numerous times already but as much as I like the mutability aspect of arc19 the storage requirements for larger collections are simply unrealistic. 
That's why I was planning on making a formal proposal to introduce either a new arc or update arc3 specs to introduce image layers metadata @fabrice102 @pbennett. 
This way instead of forcing the back-end to do the image processing and pinning the resulting file, you could simply embed metadata pointing to already pinned layer files and construct the image on the client side.
Project R4V3N website already does it this way as it's more efficient for me to have layers data stored locally and let the client do all the heavy lifting. HTML 5 canvas processing is quite fast with the current hardware so there really is no point to pin massive images to IPFS network. 
In my testing, asynchronously processing 200 unique pins 500x500 in size with 10 layers each takes about 16 seconds on standard desktop PC. 
I'm happy to discuss this further in a more relevant place but I just wanted to show you how difficult mutability really is in real life scenario.

**Comment by ChrisAntaki** [comment]
Fracctal Tamers is another great example of a project that combines the best of ARC69 and ARC19 to give their collectors better UX. No blocking JSON requests necessary

Mostly Frens chose ARC3 + ARC19, and they define **valid*** ARC3 URLs by including the "#arc3" suffix in their template URLs

Both are valid options IMO

**Comment by TommyAlex79** [comment]
> ARC19 needs to specify explicitly that the data pointed to by the reserve address is JSON

**I disagree**, please do not do that @SudoWeezy .

ARC19 is a standard to mutate the URL (by changing the CID using the reserve address).

ARC19 should be able to point to an image, or an arc3 json, or some other future arc-x json or other file format.

ARC19 is powerful and flexible and should NOT be limited to json or arc3.

The issue here is that there has been a very long debate regarding arc3 vs arc69 and this is now affecting arc19 unfortunately. Let's ignore arc69 for a second, arc19 should be able to point to any ipfs CID, image or json, etc... 

The arc19 abstract summarises this perfectly:

> This ARC describes a template substitution for URLs in ASAs, initially for ipfs:// scheme URLs allowing mutable CID replacement in rendered URLs.

Mutable CID replacement in rendered URLs. That's all!
Then if you are pointing to an arc3 json, simply follow the arc3 spec (except metadata hash).

I see why @pbennett wants people to use arc3 json if there is metadata, and I agree, if there is metadata that is the cleanest approach in my opinion. However, I think it's a huge mistake to limit Arc19 to arc3 json, to try and prevent arc69. If we want to prevent arc69 we should simply state arc69 is discouraged with arc19. Limiting arc19 to just arc3 json would be excessive, an over-reaction. 

@robdmoore , I agree, limiting arc19 to just arc3 json would "limits all kinds of potential future use cases".

> "Someone could link to an image and have no metadata and be a compliant ARC19 asset."
@pbennett , glad to see you also agree, I hope you meant it can link the image directly, and not forcibly via arc3. 

@runvnc , fyi, I fully understand why your raised this issue, not that you want that change, but that you felt you did something allowed by the standard. 

@SudoWeezy , I seem to be dragged-in always to discuss arc69, not exact sure why tbh, my contribution here is instead to try and avoid limiting arc19 to arc3 json, I think arc19 is a lot more beautiful and powerful than that.

**Comment by runvnc** [comment]
@1fatalix1 the image generated on the fly from constituent layers thing is a really interesting idea. If you make an ARC for it then I will try to support it on algonfts.art, especially if you can get some marketplace to support it. Seems like something that definitely would go in it's own ARC, whether you based it off of ARC3 or whatever.

Also thanks to the people who reaffirmed that I can still read English. Yes, metadata was implied, no, it was not specified. As I said, the missing keyword "MUST" is the key failure here for the people who wanted it to mean something else. Also the fact that the question was specifically asked and answered immediately prior to being finalized and then not contradicted.

I am very very tired of this debate though. I will probably make arc3 the default option for arc19 on my site (when I have time to implement it) just to avoid this discussion further, even if it adds 1000 HTTP requests to every page load or requires me to build my own metadata Indexer. At this point it's probably worth just about anything to not have to get into this discussion again. Probably.

**Comment by ChrisAntaki** [comment]
> ... just to avoid this discussion further, even if it adds 1000 HTTP requests to every page load

I feel like degrading the performance would have a higher chance of creators/collectors starting the discussion again, vs leaving it efficient like Fracctal Tamers, Raven, etc
