### ISSUE TITLE
Discussion for ARC-0012: Claimable Algorand Standard Assets (ASA)

### ISSUE THREAD

**Issue by SilentRhetoric** [algorandfoundation/ARCs#131]
This is the discussion thread for [ARC-0012](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0012.md).

**Comment by nullun** [comment]
Nice work @joe-p and @SilentRhetoric!

What's the reason behind returning the 0.2 Algo to the ASA creator address on redemption of the ASA? If I send USDC to someone who has yet to optin to it, why should Circle get 0.2 Algo when it's claimed? I understand that sending it back to the original sender isn't possible without state, but I'd have thought hardcoding the intended receiver of the ASA would be easier? I think this might also eliminate the need for a smart contract?

Additionally would the 2*MBR requirement only be for the first time the smart signature is used, and subsequent uses only require 0.1 Algo? If I'm nice I'd like to already prefund my address with 0.1 Algo so that all senders would only need to pay 0.1 Algo for the ASA they're choosing to send.

**Comment by SudoWeezy** [comment]
@nullun Your comment is excellent, please add it to the PR directly. I will reopen the issue when the ARC goes into the main repo.
