### ISSUE TITLE
Discussion: NFT Collections

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/ARCs#25]
This issue is meant to gather feedback on what features are needed for NFT Collections.

Please comment with any relevant info regarding needs or features you'd like to be supported.  If you're already creating collections, please describe how they're represented.

**Comment by emg110** [comment]
Some Hierarchy or semi DAG implementation via simple fields in metadata, such as `parent` as a key reference or `children` as an array of keys or even children metadata objects, would seem to be nice I think.

**Comment by DragonDev1906** [comment]
I think one of the first things to define regarding collections is the relationship to NFTs, as this may limit how it can be implemented quite a bit:
- 1-to-n relationship (a collection can contain multiple NFTs but a NFT can only be in 0 or 1 collections)
- n-to-m relationship (a collection can contain multiple NFTs and a NFT can be in multiple collections)

A n-to-m relationship would allow someone to create a collection from existing NFTs.

As for requirements a collection could have:
- Optional maximum amount of tokens as part of the collection
- Ability to add NFTs as long as the maximum amount was not reached, yet
- Limitation on who can add tokens
- Should probably have the ability to set name, description and potentially other fields
- Should probably allow for additional data (JSON?) that could for example indicate the rarity of features (which is not specific to a single NFT but relevant to the entire collection; probably what @renderjo meant)

**Comment by barnjamin** [comment]
> n-to-m relationship (a collection can contain multiple NFTs and a NFT can be in multiple collections)

For this I was thinking of a collection as 1 creator multiple NFTs all of the same theme or topic.  Is there an example of the n-m?

**Comment by emg110** [comment]
regarding `a NFT can be in multiple collections, I think it's not plausible if the collections are sellable. What happens if two collections containing the same NFT get sold on separate markets to different buyers?

**Comment by renderjo** [comment]
In programming terms. A collection would be a class, the nft would be the object/ instance of that class.

**Comment by barnjamin** [comment]
> In programming terms. A collection would be a class, the nft would be the object/ instance of that class.

This is how I was thinking of them as well.  I think unless there is a compelling example of the n-m we should assume collection means something like this.

In that regard, a collection could be embodied as a set of ASAs created by the same account, but that would limit to 1k max ASAs.  

It could also be formalized as a set of smart contracts that hold a specific ASA token representing that it is a member of the collection.  This would allow any size collection but the contract would have to enforce certain rules like disallowing xfer out of its balance.

Thoughts?

**Comment by DragonDev1906** [comment]
Would it be possible to define a collection as a set of accounts (that created NFTs)? That would circumvent the 1k ASA limit.

**Comment by barnjamin** [comment]
Potentially, but does make it more complicated to track

**Comment by TommyAlex79** [comment]
I am seeing this problem... Many collections are now exceeding the 1K limit. It would be nice for collections to be addressed, either by increasing the 1k limit or by making verifiable collections part of the ARC3 standard.

**Comment by hartmutobendorf** [comment]
To add some thoughts:

NFT collections are usually understood (like here) as closed, i.e. defined at the time of minting. These collections need some mechanism to limit the number and prevent others from creating fake additions.
- A smart contract would solve this, but is quite difficult to access when compared to ASAs and IPFS.
- The set of accounts is not that difficult for the verification operation which might be more important than keeping track of all assets.
- keeping track of all assets might also be achieved with meta data: create a signed IPFS entry that holds the IDs and signatures of all NFTs before minting, or creating a special 'index' metadata after minting that holds the addresses and ids of all minted ASAs.

There might also be a need for 'open' collections that could simply be extended by reusing the id/uuid of a specific collection. If need be: anyone can add to an existing collection.

As the n-m case was mentioned: if I understand this correctly, it would be created by a separate act of curation. Reusing the 'index' metadata idea would allow these 'curated' collections to be discovered.

**Comment by illusieve** [comment]
I'm wondering if we could make use of the manager and reserve addresses for collections. You can make a new account to mint every 1k NFTs, but each time, you link the same manager and reserve address. The manager/reserve address doesn't have to opt-in to the asset, so it shouldn't be an issue to "manage" > 1k ASAs. 

It's possible someone could come along and create fake NFTs for the collection and link to the collection's manager address to feign authenticity, but since the manager can actually manage the fake ASAs, he could remove himself, setting the manager/reserve address to undefined, making it immutable. 

Additionally, if the entire collection is planned out and won't be added to, all collection files could be added to the same ipfs folder (and would thus have the same CID). Then, in addition to checking the manager/reserve address, you could also verify if the asset in question is part of the collection because the URL should match across all assets in the collection regardless of creator address.

**Comment by DragonDev1906** [comment]
I love the idea of having another "allowed-to-create-for-collection" asset (which can also store information about the entire collection in the metadata). This would also be possible using a stateful contract storing a True value in local state for creator accounts, though then there would be no standard way to define collection metadata like the collection name/description. This would also allow the creator to make sub-collections (assets created by A and B are in collection X, assets by C and D are in collection Y and everything (A, B, C, D) is also in collection Z).

It would also be nice if the amount of collection tokens would say how many assets someone is allowed to create (999 collection asset means up to 999 tokens that can be created). Then the total amount of collection tokens is also the max amount of assets in the collection. Unfortunately, a smart contract can't see how many assets an account has created, I think. It could also give problems regarding removal of assets, should the creator make more assets than he owns collection-tokens.

One thing to consider is that a malicious creator could "drop/remove" assets from the collection by removing the collection-tokens from the account. This may be disabled by freezing the asset and removing the freeze and clawback accounts from the collection-asset, though I don't know what happens if you opt-out of an asset that is frozen (if that's possible). The creator could still remove an asset and create a new one in exchange if he is malicious and owns said asset, but I think this is less problematic than the ability to remove arbitrary assets you don't own.

**Comment by koen-vr** [comment]
How about a contract (`app`) to keep track of minted `id`'s. When combining id reservation and ASA creation into an atomic transaction it creates a link that can not be altered or faked.

Transaction Group:
1. Asset Creation transaction
2. Id reservation transaction

If someone manages to reserve/mint the `id` the group fails and the asset is not created.

With the recent publication from @gidonkatten where he splits an index (used as an `id`) into a [x, y, z} address space to target individual bits the storage space in a contract can be expanded to a max of 64.592 unique `id`'s per collection.

From the ASA we can trace back to the 'app' by looking at its creation and the group transaction that reserved the `id`.
Going from the `app` to the ASA is a bit harder, but there is a list of transactions that reserved the `id`'s and are grouped with the ASA creation.

**Comment by runvnc** [comment]
This should be greatly simplified when the PR removing the asset ceiling is removed.

Right now my understanding is that it's up to the NFT Explorer people to manually add to their database based on a list of addresses and unit names.

My suggestion is that for the standard, it is not really a requirement to support multiple collections per wallet (i.e. different unit names).

An ASA with a few standard metadata fields could identify a collection. I am the creator of https://algonfts.art, a system for automatically generating and minting NFTs, and have discussed this with AlgoT from NFT Explorer before. He had a few interesting ideas but I think for them it's not a priority since everyone goes to them directly to enter in their database.

We just need to decide what fields are required and where the ASA goes/how to find it.

My suggestion is let's just use an ARC3 NFT with the custom fields `collection_name` and `collection_description`. Anything else they put in there is optional to display. Use a note prefix like `coll-create` or something so they can be searched. Issue that transaction from the wallet containing the collection.

Many, many other interesting things are possible but they should not block the core requirement from getting out which is just identifying and describing the collection.

**Comment by whereisrysmind** [comment]
Hello Everyone,
Reviving this conversation with a proposal for ARC-0030.
https://github.com/algorandfoundation/ARCs/pull/122
Credit to @evanmaltz

**Comment by barnjamin** [comment]
closing in favor of discussion in #122
