### ISSUE TITLE
ARC3 - Non normative IPFS best practices

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/ARCs#40]
For images stored on IPFS the files may be unpinned at any time. If a user has not saved the media locally, they may lose access to it. 

We should add a non-normative comment to suggest that platforms warn users about the possibility and recommend downloading the image immediately to prevent losing access.

There may be other recommendations that make sense as well

**Comment by wheresaddie** [comment]
@barnjamin - I am wondering if this belongs more as a best practices/collector onboarding README/FAQ etc. 

I have been putting a lot of thought into the archivability of NFT/the files in which they point to, and how this reflects the legitimacy of the movement within institutions/museums (and if this even really matters to most marketplaces/artist/collectors?). In addition  considering the argument that NFTs have “solved” a long-standing problem of uniqueness and provenance simply ignores the fact that they rely on forms of trust, negotiation and authentication blah blah blah as @ChrisAntaki so correctly pointed out. 

I view the belief/concept that everything is temporal (because it is) in a few ways in the context of NFT best practices: 

- marketplaces store a central backup of the IPFS for the collectors which they offer as a sort of hot storage of the works
-  artist/auction houses have provided an encrypted drive or thumb drive with the files/source codes. Including a COA which is physical but points to the ASA hash, in addition to other conditions (such as how an artist would like to displayed, what to do if the file is corrupt or the IPFS goes down etc) 

Might something like this be more of interest?

**Comment by barnjamin** [comment]
> best practices/collector onboarding README/FAQ etc.

This makes sense, where do you think this lives though? Each marketplace links off to something or some extra thing here?

Good points to add to the document and should probably allow additions for other storage options like Arweave
