### ISSUE TITLE
Discussion for ARC-0004: ABI

### ISSUE THREAD

**Issue by fabrice102** [algorandfoundation/ARCs#44]
We're moving the discussion for ARC-0004 from #7 to here.
Draft is https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0004.md

**Comment by fabrice102** [comment]
Moving the questions out of ARC-0004 there:

* Would people prefer “Method prototype” here in order to avoid using the word “signature” again?
* Should we allow the contract description to specify methods that require an opt in
    * As a subquestion: should we allow methods to require an opt-in in some cases, but not in other cases?
* Further questions: Should it be possible to describe requirements of certain fields of the transactions named this way? For example, can the amount of recipient of a pay transaction be specified? A specific, important instance of this problem: How can logicsigs on these transactions be provided in the JSON interface?

**Comment by barnjamin** [comment]
>For example, can the amount of recipient of a pay transaction be specified?

Does it make sense to define a format to specify a 'transaction filter'? Strict comparison only to validate certain fields. 

It's come up elsewhere: 
https://github.com/algorandfoundation/ARCs/pull/41/files#r754713743

>How can logicsigs on these transactions be provided in the JSON interface?

How do you see logic sigs being used in the method?

**Comment by wheresaddie** [comment]
> Would people prefer “Method prototype” here in order to avoid using the word “signature” again?

yes. is important to delineate from my pov.

**Comment by AustP** [comment]
> Some AVM opcodes require specific values to be placed in the "foreign arrays" of the application call transaction. These three types allow methods to describe these requirements. To encode method calls that have these types as arguments, the value in question is placed in the Accounts (apat), Foreign Assets (apas), or Foreign Apps (apfa) arrays, respectively, and a uint8 containing the index of the value in the appropriate array is encoded in the normal location for this argument.

I think having a uint8 that contains the index of where the reference type is in the respective array is a little overkill. It would be much more straightforward if the order that the types appeared in the method signature was the order that the values appeared in the foreign arrays. For example, assume I have a method signature: `transfer(asset,account,account)void` which transfers an asset from the first account to the second account.

Currently, getting the asset ID requires three opcodes:

```
txna ApplicationArgs 1
btoi
txnas Assets
```

If we required the callers to put the values in the foreign arrays according to the order of the method signature, I could get the asset ID in a single opcode:

```
txna Assets 0
```

By enforcing the ordering in the foreign arrays, it also makes the method call easier. The caller doesn't have to keep track of which index in the array a reference type is, they simply include them in the order that the method signature has them listed. I also think that people will naturally include the values in the foreign arrays in the same order as they are listed in the method signature.

Therefore, I think the spec should be updated to enforce order in the foreign arrays which would make method calls easier and reduce code bloat.

**Comment by pbennett** [comment]
A contract may have any number of inner transactions, perhaps sending to accounts defined in state data of the contract. and none of which would be part of an explicit contract call.  Users will for now still need to know what the contract will reference and pass in those addresses, but there shouldn't be an assumption or mandate that foreign assets/apps be defined as part of an interface signature.

**Comment by AustP** [comment]
@pbennett I agree with you. There should be no mandate for reference types to be included in the signature. My suggestion is that *if* they are included in the signature, the caller would be required to order them according to the signature.

For example, in order to call the transfer example method from above, the caller would be required to include the `from` account as the first value in the foreign accounts array and the `to` account as the second value in the foreign accounts array.

**Comment by jannotti** [comment]
@AustP There are at least two reasons to prefer the explicit "naming" of the foreign array slot.  The first is that it allows the use of slot 0, which automatically holds the sender.  I expect this will be very common.  Even your example, `transfer(asset, account, account)` will probably want to pass the `from` account by specifying `0` most of the time.  The second reason is that it allows using the same slot more than once.  For example, the governance contract is probably going to allow a "rewardsTo" account to be specified soon (or maybe it already does).  It would be nice to avoid repeating the address in the foreign accounts array for the common case in which the `from` and `rewardsTo` are the same account. The foreign array is limited in size, and wasting block space seems bad in any event.

@pbennett This is defined for the benefit contracts that _do_ think of these resources as part of the signature.  Take, again, @AustP's example.  The asset, and the `from` and `to` addresses _are_ part of the abstract signature.  So, I think you would be advocating for a signature like `transfer(uint64,address,address)void` (note, address not account).  Such a signature asks for the values to be encoded by the "normal" rules.  However, such a contract would also need each of those values in the foreign arrays, and I can't imagine why you want a) to duplicate the values in both places and b) it to be less clear how to call this contract correctly.  If I'm understanding you right, you're making a different point than @AustP, who is just talking about how your code knows which one is the resource in question. So we are at risk of the conversation getting a bit confusing from here on out.

I take your point that in the (not too distant?) future, a contract C might invoke D and F, without wanting to make that part of its interface.  When that becomes possible, I imagine C will add a new, more concise, method that doesn't need the extra app ids that (today) must be passed in the ForeignAccounts array when calling C. But again, why pretend that's possible today? Today, those contracts _are_ part of C's interface.  Those arrays need to be properly filled, and this seems like a reasonable way to describe them. Fortunately, it is ok to overload method names with different signatures.  Again, keep in mind that this is an ABI, not API.  We're not striving for the perfect abstract programming interface, we're striving for an ironclad description of how to encode necessary binary data.

**Comment by pbennett** [comment]
I think in a use-case I have today, contract A pays out to multiple accounts via inner transactions when a particular method is called (a pay + a contract call), and the caller shouldn't have to understand those inner workings.  It's an implementation detail vs a public contract.  If a user sends 50 ALGO to contract A, and calls a method of A [which has no mention of any other account other than its 'owner' calling it], and A chooses to issue inner transactions paying 1 to account B, 2 to account C, and 47 to account D, the caller of 'A' shouldn't have to understand that relationship, nor have to encode that into the foreign accounts array as is required today.  Contract A 'may' also pay out differently depending on various state - so that can't be encoded either.  So I'm actually saying the signature would just be dosomething(uint64) - and that's it - because to the caller, the foreign accounts ('account' args) are and should be, unknowable to it.  

I understand that given todays foreign accounts requirements, the caller DOES have to know these things and I thus have to construct these calls for the user (via an exposed API for eg), but if the requirement that these inner-workings be exposed persists then it just ends up being like dosomething(uint64)  [...account].

Hopefully that help explains my perspective (or possibly muddies the existing conversation - hopefully not).

**Comment by jannotti** [comment]
I think I understand all of that - certainly that it would be preferable to let contracts do some amount of work that is not exactly specified explicitly in foreign arrays.  But I still believe that the ABI should describe how you encode the data that must be sent to a method, and until that data stops being required, the ABI should say how to encode it. In effect, the way I think about it is that *today* those resources *are* part of the binary interface to the contract, so it belongs in the ABI. I don't think this is obviously true.  I get that there's a grey zone. For example, we don't let the method describe that the third argument, and asset id, must be some particular value (the asset that this particular contract uses, for example).  We have to decide where to draw a line that effectively says: On the ABI side, we describe how to encode types, and it's up to the method's human understandable description to say something about what value for those types make sense.

In your case, I don't think you will have the same objection as @AustP . He is finding it annoying to use two extra instructions to access the resources.  You will not even be accessing from those foreign arrays.  You will be deciding what resources to touch based on contract state. So all you care about is that they appear _somewhere_ in your foreign arrays. In that case, the specificity of ABI is overkill.  You never explicitly look.

So let's be very explicit about what (I think) each of you has requested:

@AustP would prefer to not encode the position of the resource in the foreign array.  My explanation for that is that it allows callers to use the sender (index 0), and it allows multiple arguments to use the same slot in the foreign array.  Is that convincing? We _did_ consider making this implicit, I don't think it's crazy.  But we found the features I just described useful enough to go with explicit locations.

@pbennett would prefer that these resources just get encoded as usual (if they are a "real" argument to the function, else they don't even appear in the signature). This would require that they *also* be encoded in the foreign arrays to make access work. And it would require another mechanism to explain to callers they should do that for (some?) of these types.  Our decision was to introduce new types to act as that mechanism.  If you uses `asset|application|account` you are signaling the need to use foreign arrays, if you use `uint64|address` you are signaling that there is no such need and the type should just be encoded in app args.  Is that convincing? We want to save the duplicate encoding, and give the caller a bit more info about how to encode.

**Comment by pbennett** [comment]
Got it, thanks for the clarification @jannotti.  So am I correct in that if I have a contract call (today) that needs 4 foreign accounts, all referenced by inner transactions, the ABI would just need to be like:
dosomething(uint64,account,account,account,account)bool
and the method would only get 1 argument, with the rest being in foreignaccounts in order.

Then when inner transactions can reference accounts via their own state (or by getting data from a contract-to-contract call) in the future, a new version of the abi could just remove those account params.
I can accept that.

**Comment by jannotti** [comment]
The method would get the selector in ApplicationArgs[0], then an ABI encoded uint64 in ApplicationArgs[1], then it would get a single byte in each of AA[2], AA[3], AA[4]. Those bytes would indicate where in the ForeignAccounts array those accounts are placed.  @AustP's argument was that those bytes were pointless, the contract should just assume the accounts are placed in order.  I think I see agreement now that we should stick with encoding those indexes now, so that they might refer to the sender by using 0, and/or they might all refer to the same single account by using the same index.

Your (NFD's) contracts might never use those indexes at all, you might just be finding those same accounts by performing a lookup of internal state. Your code would then use the account you looked up, and it would "hope" they are in the Accounts array.  I say "hope", but of course what I really mean is that your dapp frontend knows about these rules, and made it so. (As long as something strange hasn't happened to your state in the meantime.)

**Comment by FrankSzendzielarz** [comment]
Arc4 is partially aimed at HLLs. Right now with the C# compiler I am tentatively going with the concept of SmartContractReference classes as predefined types, used as part of a method signature to reference another application. These would be subclassed according to the expected interface of the other application. For example, a developer could subclass SmartContractReference and define SomebodyElsesPriceOracleContract, exposing some methods. (Later, the tooling would support automatic generation of these reference classes based on Arc4 json formats.) The SomebodyElsesPriceOracleContract is then defined as a parameter in a smart contract method , the position of the argument in the method argument list defining the index of the foreign app array to use. The compiler converts any reference to that variable in the ApprovalProgram method body to the appropriate TEAL opcodes, eventually generating inner transactions on the basis of the imported method signatures, but for this version generating app_local_get_ex or app_global_get_ex for a field/property defined in SomebodyElsesPriceOracleContract.

I assume that generally, when accessing state expected of a 3rd party contract, the keys and value types need to be reliable?

If so, I think it would be a good idea if the Arc4 approach also dealt with state, so that it would be possible to not just auto-generate the method Interface but the interface for state getters too.

**Comment by StylishTriangles** [comment]
What is the reason for limiting the assets/application/account references?

I read that their encoding is unusual, sure, but everyone _knows_ what that encoding is.
I see this as a major limitation as it requires workarounds for some problems that look straightforward and could be common.

It's very simple to create examples of useful reference arrays:
1. `transfer(asset[], account)void` - SSC moves specific assets to another account
2. `optin(asset[])void` - opt in SSC to a list of assets (possibly as an admin)

The sad part is that there are many ways to work around this leaving contract creators with possibly many different interfaces in the wild:
1. `optin(asset)void` - just call it many times (pays more txn fees)
2. `optin(uint64[])void` - has a nice interface, just provide asset IDs kind of like in ATC, but doesn't really convey how you should call `optin`
3. `optin(uint8[])void` - tries to behave the same way as asset[], referencing specific IDs, more complicated, but allows for easier mixing asset and this evil structure in the code.

From the example above, the problem is that forbidding usage of "unusual" types in structures produces even more unusual structures and less consistent interfaces, or is simply inefficient.

**Comment by jannotti** [comment]
> What is the reason for limiting the assets/application/account references?

I suppose my reasoning was that there are currently severe limits on the number of accounts/assets/apps that can be supplied to a contract as "available" resources, so contracts that want arrays (especially dynamic arrays) of resources weren't a likely use case.  At the same time, I don't think the current ARC does anything to prevent the "obvious" encoding, were you would encode such an array the same way you'd encode a uint8 array.

For example, the interfaces you've shown:

> 1. `transfer(asset[], account)void` - SSC moves specific assets to another account
> 2. `optin(asset[])void` - opt in SSC to a list of assets (possibly as an admin)

would probably be a bad idea today.  It implies that you can send a list of, say, 10 assets.  But you can't do that because there isn't enough room in the foreign arrays.

Still, I get your point, and I would not oppose changing the spec to warn people against such interfaces, but to specify that they can be encoded as you would encode uint8 arrays/tuples.  Would you like to take a stab at a PR to explain that?

**Comment by jannotti** [comment]
> For discovery of the ABI specs, we could add to this standard some property of smart contracts, eg: a global state var labelled "Disco", or some code element, that contains the hash of the current ABI spec. That way the ABI can be sent to some standard websites, the JSON verified and then published.

There are two interesting ideas here.
1) I would like a way for a contract to "point" to its off-chain spec, stored somewhere else. Such a pointer should also contain a hash. In principle, that pointer could actually be in the byte code, rather than consume precious global state space. (For example, by embedding the pointer in the bytecblock.)

2) It might be nice for a spec that allows contracts to describe their global state encodings.  They might wish to say something like `{key: "ages", encoding: "[5]uint16"}` to indicate that the `ages` key in global state is ABI encoded as a length 5 array of uint16.

To my mind, these both belong in another ARC, as they are ways to describe data related to the contract (even though, in the case of #1, the data being described is the ABI spec.). The ARC would be a standard for describing contract data, and it might talk about global state and special encodings for data that's in the bytecode. Maybe even standardize a way to point to arbitrary metadata, as a generalization of the work going on for NFTs.

**Comment by FrankSzendzielarz** [comment]
Ok sure, I can try to put together another ARC. Never done it, can someone give me pointers , for at least point 1. 

1. I don't think the Contract should point to its spec, rather the spec should be publishable on various places and downloadable, and used in the same way OpenAPI/Swagger is used, to codegen proxy classes. It's just to publish it you need to verify that the spec really is associated with that smart contract. So eg: you could have a website like <appId>.somedomain.com and to upload there the website needs to be aware of the Arc format , monitor that address, and update/add the json (so it's not a fake file).

2.  In my mind the "getters" are part of the interface. When you read global state/local state, the keys have to be there.
3.

**Comment by ryanRfox** [comment]
@jannotti are you considering the _interface description_ JSON file or the high-level language source code (eg PyTeal) used to compile/generate both the _bytecode_ and _interface description_ as the "spec" to be referenced off-chain or just the JSON?

I definitely like the concept of committing to the spec within the bytecode. Something similar to the `#pragma version` is used within the byteblock I assume?

**Comment by jannotti** [comment]
I think you might want to have both. The interface spec is useful for simplifying calls, the source code would be useful for security assurance. The idea is to point to your source code, so that a security conscious caller could compile it themselves to ensure the on chain program is identical. Then they can understand the code more easily than by disassembling.

**Comment by FrankSzendzielarz** [comment]
After chatting about this topic on Discord,  it seems there is a good argument for wanting to point _out_ somewhere from the contract to a spec : when someone already knows the app they want to integrate with, they can look at the app itself to find the ABI spec, or anything else, that the authors consider 'official' for that app. If the only route to finding an ABI spec was via some search engine or 3rd party repository, even if the ABI spec was connected to the contract via the hash, it's more likely that phishing scenarios would occur (eg: "T1nyman contract" here). 

We could have a single external metadata file, broader than just the ABI json but including it, for example, with a single link in the bytecode. Anyway, I agree with the above this would best be in a new Arc. 

Still think the state vars should be here though ;-)

**Comment by runvnc** [comment]
Being able to search for and discover applications that meet certain needs with specific interfaces or matching certain keywords is a requirement that will become very popular once the ABI starts to be widely deployed. If there is no ARC  or standard, this need will likely be filled by whatever website or service decides to create a directory. As I mentioned in Discord, having this default to being centralized to an arbitrary service that pops up is very non-ideal. It means we are beholden to a specific company.

One very simple way would be for an application creation or update transaction to have a specific note format such as `abi4-{cid}`  with the IPFS cid pointing to the contract JSON. Then we could at least use note prefix searches on the Indexer to discover them. There could be an additional check of a global state field / bytecode check or something.

But just agreeing on any sort of note prefix changes the situation from "I guess we will just examine the bytecode or state of every single application creation/update ever, whoops I am not going to do that, we should all just lock into -- Larry's Interface Registry --" to having multiple indexing or curation services just needing to do queries against that note prefix.

**Comment by FrankSzendzielarz** [comment]
I put the new ideas in a new Arc

https://github.com/algorandfoundation/ARCs/pull/75/files

**Comment by 0xTsubi** [comment]
It would be helpful to have more examples of the contract ABI implementation, particularly for reference types and transaction types in the context of a group transaction. It would also be helpful to have examples for each of the encoding types and rules, though this is less important. 

Tangentially, is there a reason why one shouldn't use `txn Sender` instead of `txna Accounts 0`?

**Comment by FrankSzendzielarz** [comment]
HLLs will use structs/classes to represent artefacts. The implication in the arc4 spec is that objects will have to map their fields to tuples. The issue there is that an HLL method signature like List<Product> GetMyTopTenProductsToday(DateTime day) will have its corresponding method selector change as new fields or subclasses of an entity are added, It quite normal for APIs to remain without version changes if , for example, classes like Person { string FirstName, string SecondName } change to Person {string FirstName, string MiddleName, string LastName }. The method selector needs to stay the same for such cases. 

But there are two issues here: the second being there is no support for object representation. If a PyTeal app uses a custom object and exports a contract.json file for a C# app to consume (the contract.json is redundant for a PyTeal app -> Python consumer scenario because the client Python or contract-to-contract PyTeal proxy can be generated by Python tooling) , the contract.json only provides a tuple with no information to reconstruct the PyTeal object in c#. The contract.json needs to include mapping information, field and type names, much as other API specs offer.

Once the above problem is solved then the problem of method selectors can be addressed, as the method signature is compatible when optional or unknown fields are passed in.

**Comment by FrankSzendzielarz** [comment]
ARC4 says:

`(T1,T2,…,TN): A tuple of the types T1, T2, …, TN, N >= 0.`

should read:

`(T1,T2,…,TN): A tuple of the types T1, T2, …, TN, N >= 1.`

**Comment by SudoWeezy** [comment]
Finalizing ARC-4 with PR: https://github.com/algorandfoundation/ARCs/pull/181#issuecomment-1490439386
