### ISSUE TITLE
Discussion for ARC-16: standardizing traits (attributes) in token metadata

### ISSUE THREAD

**Issue by fabrice102** [algorandfoundation/ARCs#62]
This discussion follows #61 after merge of the ARC-16 as a draft.

**Comment by kcelestinomaria** [comment]
Hello @fabrice102, can I add the discussion on Asset Creation/Tokenization fields here? From the Discord? I also found a simple User Story to describe how it could work, here it goes: Imagine you have an e-commerce store you want to build on Algorand. An e-commerce page generally has listed products on its site. You basically would need to stamp or encode each product on-chain. The current offerings from the Algorand tooling are the ASA Creation SDK, and the Payment SDK, at least the best possible toolings for this at the moment. A simple process would include first inputting a hash of the product, and the value/price. However, the ASA SDK is limited in that you cannot input value(just an extra integer field), especially for our scenario we would need to convert the value/price from a fiat currency, take USD, to Algos or other ASAs on the fly before sending that transaction on-chain so that smart contracts(where the business logic is) can comfortably act on that price. The payment SDK can work, since it has a transaction note field, check this demo from RandLabs where they put prices on the transaction note[https://github.com/randlabs/algo-price-oracle]. Unfortunately for the payment SDK though, it does not have a hash field, and of all solutions, it is the worst since it is meant for Algos and not other ASAs. Lastly, the solution I personally had working around this, was just taking input from the user through a form, converting it into bytes, and then filling it into the arguments array contained in the application call transaction to the smart contract that will act on it, the cons of this approach is that you still do not get a record of the asset/product on-chain.

**Comment by robdmoore** [comment]
Love this standard.

One comment: for backwards compatibility I think any metadata that doesn't have a `traits` value in it should be treated as previous (i.e. they are all traits).

**Comment by SudoWeezy** [comment]
I am moving the ARC 16 to `Last Call`. It is already widely used.

**Comment by ChrisAntaki** [comment]
Nice and simple, no complaints. I agree with @robdmoore 's suggestion

**Comment by SudoWeezy** [comment]
Thanks for the feedback, I have added the backward compatibility.
