### ISSUE TITLE
Discussion for ARC-0019: NFT ASA URL templating proposal for mutable IPFS CID replacement in URLs.

### ISSUE THREAD

**Issue by fabrice102** [algorandfoundation/ARCs#73]
Continuing the discussion from the PR #63 now that it has been merged as draft.

One important question for me is:
resulting NFT will no more be a valid ARC-3 asset, because the metadata hash will not be valid after mutation.
Since the CID contains the hash, there is no security issue. So the main question I would say is how to document this properly and what convention to choose for the metadata hash in that case:

* Should it be the 0 string to make it clear it's mutable and we are not using ARC-3 metadata hash?
* Should it be the metadata hash of the initial JSON metadata?

**Comment by pbennett** [comment]
Right, because the CID itself is the hash of the content and is already immutable, the metadataHash isn't necessary for data verification.  
I'm inclined to say the metadataHash should just be empty.  The 'intiial json metadata' would likely be wrong quite quickly (at least in my planned use case), which I think would cause far more confusion than it just not being set as it would mostly be wrong.  If it's incorrect then what purpose does it serve?
Since in a normal ASA, the metadataHash would be a variant of the hashing provided by IPFS anyway, just having it be unset seems fine to me.

**Comment by pbennett** [comment]
Should we just update the spec and say the metaDataHash should be 0 ?

AlgoXNFT, AlgoExplorer support ARC19 now.  Others should announce soon.  NFDs are using it on testnet now and I expect a number of NFT minters to use it shortly as well.

What's the next step at this point @fabrice102 ?

**Comment by fabrice102** [comment]
Can you have a quick look at #116 ?
