### ISSUE TITLE
Transaction Group Payload and ABI URI specification

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/ARCs#82]
We should enable the ability to encode multiple transactions representing an atomic group transaction in a compact form suitable for something like a QR code.

The current URI defined is limited to payments and some asset transfers and only one may be encoded in a single payload
https://developer.algorand.org/docs/get-details/transactions/payment_prompts/

The following may represent a starting point for discussion for defining such a data structure

```json
{
  "version": "1.0", 
  "transactions": [
    "algorand-abi://123/repeat_message?message={string:hello}&times={uint16:3}", 
    "algorand-abi://123/sell?id={asset:456}"
  ]
}
```

In the above example two application calls are described for a group. Both reference an application id, method, and set of arguments. The resultant transaction should conform to the ABI spec described in arc4.

Other transaction types should be supported.  The fields for the transactions should be distinguishable from the arguments for an application.

Should we support undefined values? This would require the wallet software to allow the user to select from a range or set of values. How would those be denoted?

To start I've hacked up a small demo to parse the URIs or generate the payload.
https://github.com/barnjamin/abi-uri

**Comment by barnjamin** [comment]
Another thing to consider is how to encode an `opt in` without getting the address ahead of time.  The payload should be self contained and only require things like the scanners address and consensus parameters.

**Comment by FrankSzendzielarz** [comment]
Sorry since my 1st milestone I have been briefly detached from online discussions and now reorientating myself for new tasks ahead. I would otherwise have looked at this earlier. Can you give some real world context to this? Some use cases? I find it a bit difficult to think about atomic transactions in a QR code without understanding the intention behind it and goals.

**Comment by barnjamin** [comment]
A couple examples might be:

An atomic group to allow an in person NFT drop using a single QR code with no website required
Transactions:
1) an opt in from the intended receiver to the asset
2) an application call to an app that will xfer the asset

An atomic swap in person between two parties without needing a facilitator
Transactions:
1) Asset A from Alice, transaction is prepared and signed transaction by Alice 
2) Asset B from Bob,  is an unsigned transaction where Bob is the sender and recipient is Alice

**Comment by dist1ll** [comment]
I think we should go for base64-encoded message pack in the URI, while still maintaining backwards compatibility with the previous way. Something like

```bash
# payment txn
algorand://TMTAD6N22HCS2LKH7677L2KFLT3PAQWY6M4JFQFXQS32ECBFC23F57RYX4?amount=150500000

# raw msg-pack txn
algorand://raw/dGhpcyBpcyBhbiBBbGdvcmFuZCB0cmFuc2FjdGlvbiBpbiBtc2dwYWNrIGZvcm1hdA==
```

I think keeping the URI scheme is a good thing. Might prove useful for deep links or multi-chain wallets.

**Comment by barnjamin** [comment]
```
algorand://raw/dGhpcyBpcyBhbiBBbGdvcmFuZCB0cmFuc2FjdGlvbiBpbiBtc2dwYWNrIGZvcm1hdA==
```
This is good.  

What should we do for user defined parameters? Initially I thought some special string but not all fields we may want the user to define are string type.


Set the user-defined fields as parameters, possibly with a set of expected values? 
```
algorand://raw/dGhpcyBpcyBhbiBBbGdvcmFuZCB0cmFuc2FjdGlvbiBpbiBtc2dwYWNrIGZvcm1hdA==?sender=me&arg[n]={uint8}
```

**Comment by dist1ll** [comment]
Yeah, user-defined fields as params sound good. In `arg[n]={uint8}` what is `n`? Some kind of label for the argument?

**Comment by barnjamin** [comment]
For an ABI call specifically it'd be a reference to the index in the arguments array of the transaction. There may be a single parameter that should be specified by the user

**Comment by fabrice102** [comment]
I like the base64 of msgpack. This works great when you know all the information in advance, including the sender.

If you don't, it looks like there is a need for templating.
Do you have concrete examples that would require such user-defined fields?

Use cases may become very complex:
* how to ask the same user-defined field to be used in multiple locations?
* how to use a user-defined field inside a more complex ABI-serialized object?
* how to indicate which transactions are in the same group, in case multiple groups are sent?

One solution may be to extend the tx structure: instead of having fields map directly to their value, fields are now structure themselves `{"v": ...}` where `v` is the actual value for fixed-field-value, `{"t": "template"}`, where `"template"` is a full-template language. 
Default fields are ignored.
Groups of groups are array of arrays.
For example, to send a single transaction with a variable amount, you use the base64 of msgpack of:

```
[
  [
    {
      "txn": {
        "rcv": {"v": the 32-byte receiver address},
        "amt": {"t": "{amount:uint64}"}
      }
    }
  ]
]
```
(this is a list of one group transaction where the receiver is fixed and the amount is user-defined, `"txn"`, `"rcv"`, and `"amt"` are the names used in the msgpack of real transactions; the other fields are default ones and not mentioned)

The wallet displays a user-defined field for the amount.

But this opens a lot of questions also regarding security.
User-defined fields may be quite misleading via their name for example.

The user would fill in the user-defined fields first and there would be a big warning to ask the user to review the transactions and that the meaning of the user-defined fields may be misleading.
How to ensure the user does not get misled looks quite non-straightforward to me.

**Comment by barnjamin** [comment]
Good point, I hadn't considered some of these complications. 

I'd like to have something quite simple to suite "most" use cases. 

Maybe for the first iteration we can limit the user definable fields to those the wallet may easily populate. Sender, valid rounds, and fee for example?

I'd definitely like to avoid defining a template language 😅

**Comment by FrankSzendzielarz** [comment]
So the use cases you are envisaging include offline scenarios? E.g. the asset txfer grp txn is printed on a wall at an art exhibition as a QR code. Solutions to the above problems must involve compact sharing of information right? As opposed to eg animating QR or other wallet to wallet streaming methods?

**Comment by FrankSzendzielarz** [comment]
Perhaps another general approach could be to look at this as a method call with parameters.

You could have base64 encoded raw transactions, even including Arc4 argument lists >15 , supplemented with an ABI method parameter list as a header, eg: 

`{ "type": "uint64", "name": "a", "desc": "Enter a random number to try and win" },
        { "type": "uint64", "name": "b", "desc": "Enter the amount you want to bet" }`
        
 Then finally there could be substitution rule lists. eg: "tx.tx1.arg1": "0"  ( substitute the amt field of grp tx1 with argument 0)
 
 If the subtitution rule specified eg: arg16 for an app call transaction then the app/wallet knows to decode arg15 and recode it.
  
 This could perhaps help mitigate the spoofing/phishing scenarios by allowing the app to issue warnings depending on the subsitution rule list an known group transaction patterns. Thinking aloud, it might be worth defining specific scenarios (eg: interperson NFT drop) and including that information in the QR code as a hint to the app/wallet, to recognise abuse of field.

**Comment by yigitguler** [comment]
At Pera Wallet, we are getting frequent requests to add support for supporting opt-in QR codes. This feature can have multiple use cases; simple website integrations, offline distributions like conferences, etc...

The user should just scan the QR and the app will create an opt-in request for a special asset. 

It would be great to determine a format before completing the multi-transaction support.

Maybe we can have a format like
`algorand://?action=opt-in&asset=45`
or
`algorand://?opt-in=45`

Any thoughts?

**Comment by barnjamin** [comment]
@yigitguler Would we just assume that the `//?` denotes their own address?

Would you be open to `algorand://raw?{b64 encoded axfer with asset id populated but asnd/arcv blank or with special values}` ? 

We can start with simple transactions first (no abi calls) but I'd be worried if we went straight to opt in special cases we'd have to support some weird backwards compat stuff

**Comment by yigitguler** [comment]
@barnjamin assuming `//?`  as users own address looks okay to me but sooner or later, we may need a special keyword in order to represent user's own address.  Example:

> Scan this QR to send yourself an empty pay transaction with special note field. 

We can also use the raw format, but for simplicity, as a last addition, we may think to add opt-in transactions to the simple QR code format.

Also, In the past, we were discussing a protocol with Jason Paulos in order to send complex transactions, but we did not proceed with it. The idea was to determine a standardized system that will allow users to put their complex transactions at a specific HTTP location and use the QR code as a pointer to that transaction bundle. This system is more complex but allows an unlimited amount of complex transactions to be sent using easy-to-scan QR codes.

So for the short-term, I think it would be great if we could find a way to support simple opt-in requests. We are open to any recommendations. `//?opt-in=45` seems reasonable to us, but if you have any suggestions, we will be grateful.

**Comment by barnjamin** [comment]
@jasonpaulos thoughts on this?

**Comment by barnjamin** [comment]
@yigitguler If we did assume the `//?` to be receiver of "me" I think there would be no need for the special opt-in parameter since the transaction URI could just be

`algorand://?amount=0&asset=45`

Where the sender is default "me" but it would still take a modification to the URI spec defined [here](https://developer.algorand.org/docs/get-details/transactions/payment_prompts/) to allow the `//?`

**Comment by yigitguler** [comment]
Sounds good to me. Should I open a PR?

**Comment by jasonpaulos** [comment]
I'm a little late to the conversation, but I can clarify and give my opinions on a few things.

### Opting in with a URI

I think this is is a great feature to have and should be the top priority when considering URI improvements. A while ago I made this proposal that could enable it: https://github.com/algorand/docs/pull/389

Right now the `algorand://` URI scheme only supports a URI like this, `algorand://{receiver-addr}?amount={amount}`, which prompts a wallet to transfer an asset or Algos to the addresses in that URI.

The main idea from that proposal is that we could introduce top-level "paths" to the existing `algorand://` URI scheme. That way the payment I mentioned before could be `algorand://pay/{receiver-addr}?amount={amount}` (note that for backwards compatibility we'd still want to support existing URIs with no top-level path), and an asset or app opt-in could be `algorand://optin/{asset-or-app-id}`. One thing the proposal doesn't allow is specifying a note field value for the opt-in transaction, but I think this could be made possible if there's a need for it.

The great thing about this approach is that it's independent of the sender's address. You could print the same URI as a QR code and distribute to many people and they'd all be able to opt into the desired resource, no matter when they scan the QR code.

### Embedding arbitrary transactions in URIs

The `algorand://raw/...` approach is nice (though I'd suggest renaming to something like `algorand://signtxn`), but it does have caveats. The ones on my mind are:
1. The URI is tied to a specific sender
2. The URI has a fixed expiration date: the last valid round of the embedded transaction
3. There is no opportunity for the user to provide any input
4. The URI can grow prohibitively large for some transactions (e.g. an app creation with 8 kilobytes of program code)

Because of 1 and 2, this format is better for websites/apps that are already familiar with the user, and that interact with the user in real time. You'd never want to print out this URI as a QR code and distribute to multiple people.

Due to these restrictions, I don't think 3 is that big of a concern, since if the user is already interacting in real time with a website/app, that website/app can just ask the user for any custom inputs it needs.

So while I do think this format is useful, its scope it much more limited.

**Comment by spencercap** [comment]
digging this convo! SUPER down the the raw base64 URI. 
got here from some thoughts i had on @barnjamin's abi-uri repo posted here: https://github.com/barnjamin/abi-uri/issues/2 

i agree that all transaction fields could be query params + as stated previously, select base paths could serve specific utilities (it seems the `/pay` or `/send` is the default currently). since opting-in is the same as sending yourself 0 units of x asset `algorand://opt-in?apas=asst_123` == `algorand://?amount=0&xaid=asst_123`. these kinds of shortcuts can be helpful. 

for method calling, i'm now imagining that the schema could be: (going off of https://github.com/barnjamin/abi-uri/issues/2):
`algorand://abi-call/APP_ID/METHOD_SELECTOR?args=arg_1,arg_2&note=some%20not%20so%20secret%20msg&apat=acct_xyz&gen=testnet-v1.0`

--- 

another helpful feature for URI deep linking would be importing an account into the signer app (Pera) w something like:
`algorand://import?mnemonic=one%20two%20three%20...%20twentyfive`
so that users could click a link (say, in an email or dapp) to add an account instead of scanning a mnemonic QR which isn't easy on a single mobile device for example

**Comment by barnjamin** [comment]
Also for reference https://github.com/algorand/docs/pull/804 from @yigitguler aimed to get opt in working

**Comment by jannotti** [comment]
Since asset opt-ins are just zero pays of the asset, the existing QR spec
is tantalizingly close to being enough to describe them.  If I recall
correctly, the only thing preventing it was that the wallet disallowed
them, perhaps because they had a zero amount?

**Comment by yigitguler** [comment]
The problematic part was that the QR code format was mandating a receiver account.

**Comment by yigitguler** [comment]
Yes @spencercap, this is thanks to this discussion.
